apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ab
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ab
    spec:
      containers:
        - name: ab
          image: 'gcr.io/sj-kube-1234/ab:v1'
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              path: /accounts/status
              port: 8090
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: ab-service
  labels:
    name: ab-service
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  selector:
    app: ab
  type: LoadBalancer
